### ISSUE TITLE
live calculator is 404

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/js-jquery-basics-lab#4]
The last word in the lab is a link. It currently serves a 404. Not sure how to fix it myself, or I would.
Link: http://flatiron-school-curriculum.github.io/fe-jquery-user-input-calc/

<img width="873" alt="screen shot 2016-02-03 at 2 33 31 pm" src="https://cloud.githubusercontent.com/assets/14326883/12783691/3a06effe-ca83-11e5-9bf1-e2561421e40f.png">

**Comment by AnnJohn** [comment]
thanks for catching that @onyoo. We updated the link.
