### ISSUE TITLE
Script src not found

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/js-jquery-basics-lab#5]
Line 34 of index.html reads:

```
  <script src="js/calc.js"></script>
```

and produces:

<img width="1255" alt="screen shot 2016-02-03 at 2 58 42 pm" src="https://cloud.githubusercontent.com/assets/14326883/12784307/b58ea452-ca86-11e5-8326-5954d026aeec.png">

To fix this problem:

```
  <script src="js/script.js"></script>
```

because the js file is called 'script.js'

**Comment by onyoo** [comment]
Changing the script src to script.js fixed the problem for getting functions to show in the browser, but the specs, for some reason, require the file to be called 'calc.js'. Renaming the 'script.js' file to 'calc.js' file fixes the problem.

<img width="1251" alt="screen shot 2016-02-03 at 4 22 40 pm" src="https://cloud.githubusercontent.com/assets/14326883/12786701/80dacfcc-ca92-11e5-8a74-20a71b0a32c2.png">

I don't know why the first student didn't report this...

<img width="1087" alt="screen shot 2016-02-03 at 4 28 21 pm" src="https://cloud.githubusercontent.com/assets/14326883/12786857/340457c6-ca93-11e5-81e7-f35d9539175a.png">

**Comment by AnnJohn** [comment]
thanks @onyoo. will look at this soon.
